### ISSUE TITLE
Sum all 

### ISSUE THREAD

**Issue by huashiyiqike** [dmlc/mshadow#13]
Could there be a sum all function that can give the sum of elements in tensor? Or I missed it? It is useful for MSE calculations. Otherwise  loops are inevitable like follows, which may be inefficient:

```
    tpv=sumall_except_dim<0>(F<Abs>(V));
    tpv2=sumall_except_dim<0>(F<sme>(V));
    for(int i=0;i<V.shape.shape_[0];i++){
        err+=tpv[i];
        err2+=tpv2[i];
    }
```

**Comment by tqchen** [comment]
Currently there is no such function, due to the fact that all reduction in GPU is not trivial. 
Sum all of 1D vector, however, is provided in BLAS, and should be ported to mshadow.

In terms of efficiency, most of the evaluation could be done in CPU, and code like yours should not become bottle-neck(depending on task, for neuralnet, the bottleneck is in matrix multiplication). But I agree it is a bit length:)

**Comment by huashiyiqike** [comment]
Seems that the code above cannot run with GPU, the tpv[i] will simply terminate the program. 
The temp value initialization and destruction is also too costly. Though my hands are tight, I want to implement the sumall function but it seems not trivial.

**Comment by tqchen** [comment]
Yes, normally I will copy the data to CPU, to do the job

**Comment by huashiyiqike** [comment]
cublasinit() fails for no reason, it worked before. I will move from cuda5.5 to cuda6.5

**Comment by huashiyiqike** [comment]
It is my problem. I reinstalled cuda5.5 and it works great now. I didn't try cuda6.5 yet.
