### ISSUE TITLE
Why the default GPU stream was used?

### ISSUE THREAD

**Issue by loveisp** [dmlc/mshadow#56]
When I compile and run the "mshadow/test/test.cu", it tells me:
"Default GPU stream was used when MSHADOW_FORCE_STREAM was on".
I don't know why the stream was used and how could I make it unused? I just turn off MSHADOW_FORCE_STREAM now. Doing so will make the performance worse? Thanks.

**Comment by tqchen** [comment]
The MSHADOW_FORCE_STREAM  forces us to use the CUDA stream, which is necessary way to run multiple kernels in parallel. It is also needed to run the blas kernel for now due to the update to new cublas API.

In general, it is a good idea to always allocate and set_stream to the Tensors so operations are run on streams. MSHADOW_FORCE_STREAM   enforce that by runtime check. But it is fine to switch it off and normally it won't hurt performance as long as you do not write stream related codes

**Comment by loveisp** [comment]
OK. Thanks much.
