### ISSUE TITLE
Use GPU To Random a tensor when shape is odd error

### ISSUE THREAD

**Issue by reyoung** [dmlc/mshadow#6]
Error Code Shows like that

``` C++
InitTensorEngine(0);
TensorContainer<gpu,1> tmp;
tmp.Resize(Shape1(1));  // 1 Or any odd value
Random<mshadow::gpu> rnd(0);
rnd.SampleGaussian(tmp, 0, 0.1);
ShutdownTensorEngine();
```

The error code is CURAND_STATUS_LENGTH_NOT_MULTIPLE. The error line maybe is [here](https://github.com/tqchen/mshadow/blob/master/mshadow/tensor_random.h#L257).

**Comment by reyoung** [comment]
Is this a bug or feature? I can write a patch if you want.

**Comment by antinucleon** [comment]
The param for `SampleGaussain` and `SampleUniform` is `Tensor<xpu,dim>`.
You are using `TensorContainer`, so you should use `uniform` or `gaussian` expression like `rnd.gaussian(tmp, mu, sigma)`

**Comment by tqchen** [comment]
This seems to be a BUG, TensorContainer should work here. I guess there are some restrictions in CURAND that we overlooked...

**Comment by reyoung** [comment]
I made a pull request to fix it.

**Comment by tqchen** [comment]
Thanks. @reyoung!! I make some [further changes](https://github.com/tqchen/mshadow/commit/b998f9c4315e4a32b64ebdc995c421f6650c0a3a#diff-dbc4b2028e160f240ef28c16c76091ca) based on your patch . Can you check if it works correctly now? 
I would like to know the reason why this happens, my guess is that when ever we put odd size into curand's gaussian random number generator, it will hits that error(due to fact that gaussian rnd must be generated in pairs), it would be great if we could test that.

**Comment by reyoung** [comment]
It is not correctly now. The error shows 'Error:an illegal memory access was encountered'.  It seems the buffer_ is already freed.

**Comment by reyoung** [comment]
The code that will make this error occurred shows as follow.

``` C++
    InitTensorEngine(0);
    TensorContainer<gpu,1> tmp;
    tmp.Resize(Shape1(3));  // 1 Or any odd value
    Random<mshadow::gpu> rnd(0);
    rnd.SampleGaussian(tmp, 0, 0.1);
    TensorContainer<cpu,1> b;
    b.Resize(tmp.shape);
    Copy(b,tmp);
    cout<<b[0]<<endl;
    ShutdownTensorEngine();
```

**Comment by tqchen** [comment]
Thanks.. seems I made a wrong fix, I pushed another patch to the code.

**Comment by tqchen** [comment]
This issue is fixed by newest patch.
